version: 0.6.2-beta-{build}
os: Visual Studio 2015
clone_depth: 10
clone_folder: C:\projects\CacheManager\
install:
- cmd: C:\projects\CacheManager\tools\redis\install-service.cmd
build_script:
- cmd: C:\projects\CacheManager\build.cmd --quiet verify
test: off
artifacts:
- path: artifacts\build\
deploy: off